### PR TITLE
fix to center align of a progress indicator

### PR DESCRIPTION
**Pull request by jnhwkim**
th -e 'for i =1,100 do xlua.progress(i,100) end'
    [============= 100/100 ===========>] Tot: 0ms | Step: 0ms

### CODE REVIEW

**Comment by lucasb-eyer** [comment]
lgtm, sorry for that oversight!

**Comment by jnhwkim** [comment]
@lucasb-eyer you're welcome!

**Comment by soumith** [comment]
Thanks.

**Comment by jnhwkim** [comment]
What a beautiful!

**Pull request merged**
